- README.md
> Fixes Hyperterm Website Link

- README.md
> Adding Solarized Dark Theme

- README.md
https://github.com/sindresorhus/hyperterm-snazzy
> Added hyperterm-snazzy to Themes

- README.md
> Fix awesome-node link

- README.md
https://github.com/amio/hyperterm-blink
Thanks!
> Add `Hyperterm-blink` to packages.

- README.md
https://github.com/webmatze/hyperborder
> add hyperborder link

- README.md
> add hyperseti to themes

- README.md
`hypercwd` opens new tabs with the same directory as your current tab
> Add `hypercwd` to list of packages

- README.md
https://github.com/sibartlett/hyperterm-1password
> Add hyperterm-1password plugin

- README.md
> Add hpm – A plugin manager

- .travis.yml
Adding .travis.yml with the [awesome_bot](https://github.com/dkhamsing/awesome_bot#validate-pull-requests) Ruby script to validate links.
> Create .travis.yml with awesome links

- README.md
This package is pretty awesome, it allows one to backup all their very important settings (read **_awesome hyperterm_ plugins**) to Github and restore them. Great for keeping track of changes, keeping the same configuration on multiple machines, and preventing lost configs.
> Add `hyperterm-sync-settings` to Packages List

- README.md
The theme changes based on current color of your Philips Hue lights!
> Add HyperHue Theme (Philips Hue integration)

- README.md
> Add hyperpunk theme

- README.md
This pull request adds a link to the hyperterm-wp-theme
> Add hyperterm-wp-theme to the themes list

- README.md
Updated the README to include hyperblue theme
> Add hyperblue theme

- README.md
- [ x] The title for my package or theme uses its npm title (hyperterm-plugin-example)
- [ x] The link for my package or theme uses the npmjs.com link (https://npmjs.com/package/hyperterm-plugin-example)
- [ x] There is a visual representation of what my plugin does in the repo. (Plugin: screenshot or gif || Theme: screenshot of the colors within HyperTerm)
- [x ] **VERY IMPORTANT:** I've written a short (one sentence) description for my package or theme of why it's awesome and deserves to be on the list.
- [hyperterm-duotone-darkspace](https://npmjs.com/package/hypterterm-duotone-darkspace)
> Adds hyperterm-duotone-darkspace theme

- README.md
> Give hpm more visibility

- README.md
> Added hyperambient to the theme list

- README.md
> Add hyperterm-overlay

- README.md
So as to why it's `awesome-sauce`
- It's easy on the eyes & so damn pretty :)
- User overridable configuration
- Expanded tab styling in progress
- Linted & Tested
- CI validated on Node v4 - v6 
- Coverage on codecod.io ( Only time I'm ever going to hit 100% coverage :P )
> Add base16-tomorrow-dark Theme

- README.md
> `config-hyperterm`

- README.md
Closes #26.
> https://github.com/Leeds-eBooks/hyperterm-firewatch
> Add hyperterm-firewatch theme

- README.md
Hyperterm Material : A material design inspired theme plugin for HyperTerm.
https://github.com/dperrera/hyperterm-material
> Add hyperterm-material theme

- README.md
> Adds hyperterm-sourcerer to the themes list

- README.md
> Add hyperterm-summon

- README.md
> Add hyperterm-dark-dracula theme

- README.md
> Added hyperterm-paste

- README.md
Adding an awesome HyperTerm integration, like the 1password one, but for Lastpass! It has a very nice UI to login and autofill passwords and other information.
> Add `hyperterm-lastpass` to Packages List

- README.md
This plugin enables hyperterm to be able to use scroll wheel to scroll in git diff, nano etc.
This useful feature is available in terminal.app and iTerms, but not in hyperterm.
So I believe this is a must have plugin for people using hyperterm.
> Add hyperterm-alternatescroll package

- README.md
Nothing added, just removed two duplicate entries in the packages section.
Both of these entries are already listed two lines above.
PS: thanks for this awesome list! 🎉
> Removed duplicate packages

- README.md
Added hyper-dibdabs. It is a useful plugin to add a colored dot to indicate different processes. It helps me visually determine which tab is connected to SSH or not.
> Added hyper-dibdabs

- README.md
Added the cobalt2 colour scheme to the themes section.
> added Cobalt2 Theme

- README.md
This theme is awesome because it uses a custom [`hyperborder`](https://github.com/webmatze/hyperborder) and some simply fresh colours 😁
> add hyperterm-unlease theme

- README.md
Correct typo in `hyperterm-cobalt2`.
> Correct typo in hyperterm-cobalt2

- README.md
I am adding my Hyperterm theme `hyperterm-zenburn2` to the list.
> Adding theme hyperterm-zenburn2

- README.md
> Added hyperterm-tabs package

- README.md
> Remove duplicated hyperterm-overlay

- README.md
Add Hypersolar-dark to themes list. I made it and think it's awesome enough to be included here (although I'm probably biased). It's pleasing to my eye, and I receive comments about it whenever someone is passing my desk, so it must do something right.
I haven't added a screenshot to the README, as I couldn't see a useful way of contributing that, but there are some up there that you're welcome to use.
Github link -- https://github.com/lewiscowper/hypersolar-dark
> (Theme) Add hypersolar-dark to themes list

- README.md
Hey @bnb!
Just noticed that the 'know of any other packages? add it!' line was in the wrong place, so I move it to the bottom of the package list.
✨ Hope this helps! ✨
> fix(readme): move 'add it!' to bottom of package list

- README.md
> Add hyperlinks package

- README.md
> Added the hyperterm-earthsong theme

- README.md
> Add hyperterm-retro theme.

- README.md
> Add hyperterm-crosshair package

- README.md
> Add hyperterm-cursor

- README.md
> Added hyperterm-base16-ocean-saturated theme

- README.md
> Added hyperterm-adventurous to the theme list

- README.md
Was wondering if you could add my theme to the list? It's not very popular, but at least it's something 😄
> Add hyperterm-hipster theme to list

- README.md
> Added htyt to packages list

- README.md
> added hyperterm-tab-cwd

- README.md
Change hyperterm-dark-dracula to hyper-dark-dracula
> Change hyperterm-dark-dracula to hyper-dark-dracula

- README.md
> hyperterm-solarized-dark → hyper-solarized-dark

- README.md
Renamed hyperterm-materialshell to hyper-materialshell, updated link and repository name.
> Update materialshell link and name

- README.md
Change wrong name hyper theme hyper-dark-dracule to hyper-dark-dracula
> Change wrong name hyper theme hyper-dark-dracule to hyper-dark-dracula

- README.md
> Added hypersixteen.

- README.md
Double of "Know of another Hyperterm package? Help add it!" in "Packages" removed.
> Removed double entry of "help add" field.

- README.md
> Add hyper-atom-dark-transparent theme

- README.md
Since I'm not adding an plugin or theme, I'm not going to use the checklist 😄 
I've noticed that the htyt Plugin is twice in the list so I removed one of the entries.
> Removed duplicate (htyt Plugin)

- README.md
> Add hyperterm-material-spacegray

- README.md
https://github.com/chrisdothtml/hyper-stylesheet
> adding hyper-stylesheet

- README.md
> Add Hyper-criollo theme

- README.md
> adding Ganymede

- README.md
> Add link to theme browser

- README.md
A 10% chance of getting hit with the John Cena theme when opening tabs, windows and splits.
https://github.com/Cwright017/hyper-john
> Add John Cena plugin to list

- README.md
https://www.npmjs.com/package/hyperterm-blink => https://www.npmjs.com/package/hyper-blink
> hyperterm-blink has been renamed to hyper-blink

- README.md
Add a Hyper theme inspired by a galaxy far far away
> Add an-old-hype theme

- README.md
New package added to the list of themes for Hyper
> Link to Flat Theme 2 for Hyper

- README.md
> Add hyper-aww theme

- README.md
Add a Hyperterm theme based on the [Ayu Theme for Sublime Text](https://github.com/dempfi/ayu#readme).
> Add hyperterm-ayu theme

- README.md
Reverts bnb/awesome-hyper#104, somehow shit got trippy
> Revert "added hyperterm-clicky"

- README.md
> add hyper-autohide-tabs plugin

- README.md
This PR adds the hyper-hybrid-reduced-contrast theme to the themes list!
Happy to move it down to the bottom of the list, but thought it would make more sense next to its sibling standard hybrid theme. Let me know!
> Add hyper-hybrid-reduced-contrast theme

- README.md
A Theme based on the RamdaJS REPL
NPM: https://www.npmjs.com/package/hyper-ramda
Git: https://github.com/ntwcklng/hyper-ramda
> Add hyper-ramda Theme

- README.md
> added hyper-statusline package

- README.md
> Add hyper-peacock theme

- README.md
NOTE: it's not mine but think these themes deserve a place here
> Added hyper-sierra and hyper-sierra-vibrancy theme

- README.md
Removes the window header for more space and less distraction.
https://github.com/jancborchardt/hyperminimal
> add hyperminimal

- README.md
> Add hyper-thirtyone theme

- README.md
> Add hyperblue-vibrancy

- README.md
> add hyperterm-gooey theme to the themes list

- README.md
https://github.com/mrMetalWood/hyper-command-gifs
https://www.npmjs.com/package/hyper-command-gifs
> Add hyper-command-gifs package

- README.md
Ref: https://twitter.com/rauchg/status/813486527346974720
> New: Add hypernpm package

- CONTRIBUTING.md
I stumbled upon a typo in `CONTRIBUTING.md`, then I found the sentence confusing, so I rephrased it a little bit.
> Fixed a typo + little bit of rephrasing on CONTRIBUTING.md

- README.md
> Add hypernasa package

- README.md
> Add hyper-autoprofile package

- README.md
Add 'hyper-startup' as a package.
- [unnecessary] There is a visual representation of what my plugin or theme does in the repo. (Plugin: screenshot or gif || Theme: screenshot of the theme applied to Hyper)
> Add hyper-startup

- README.md
Addresses #141.
I added a new `Development` category to the original proposal.
Also added a missing whitespace for "check out" in the intro.
> Package categories

- README.md
> Adding solarized light

- README.md
> Add `hyperterm-mild-dark` to Themes

- README.md
> added hyper-tabs-enhanced

- README.md
[PaperColor](https://github.com/NLKNguyen/papercolor-theme) for Hyper.
> Add `hyper-papercolor` theme

- README.md
Pretty window controls from the Arc Dark theme for hyper
> Add hyper-arc-dark-controls to customization

- README.md
> add hyper-chesterish

- README.md
Brings Terminal.app look and feel to Hyper.
> Add `hyper-terminal-tabs` customization

- README.md
> Add hyper-scrollbar to Customization

- README.md
Replaces reference to deprecated hyperterm-sync-settings with current hyper-sync-settings
> Replace deprecated hyperterm-sync-settings

- README.md
I was reading the [JavaScript version of Clean Code](https://github.com/ryanmcdermott/clean-code-javascript) the other day and thought the "back to top" anchors were a nice addition, very convenient.
The navigation should be even easier with these.
What do you think?
> Add "back to top" anchors

- README.md
npm url: https://www.npmjs.com/package/hyper-fileio
> Added Hyper-fileio to Productivity list

- README.md
From the repository at https://github.com/Aaronius/hyper-cat.
> Added hyper-cat to Fun section

- README.md
> Added hyper-nord Theme

- README.md
Add minimalist `hyper-midnight` theme to list of themes.
> Add midnight theme

- README.md
https://www.npmjs.com/package/hyper-captain-sweetheart
> add hyper-captain-sweetheart theme

- README.md
> Add hyperterm-dark-fusion to Themes list

- README.md
> Add hyper-macos theme

- README.md
> Added hyper-frontend-delight theme

- README.md
I left other sections untouched since there might be some recommendation order, but I am pretty sure that the themes section would be better if everything is listed in alphabetical order.
> List themes in alphabetical order

- README.md
> Add hyper-always-on-top

- README.md
> Add hyperatompunk

- README.md
> Update hyper-pane description

- README.md
No screenshot (needs video to properly show), but it will be added when I get a chance!
> Add hyper-alt-click

- README.md
3 packages have a github link.
Replaced by npmjs links
> Fix some packages URL (replace github by npmjs)

- README.md
https://github.com/magus/hyper-transparent-dynamic
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bnb/awesome-hyper/225)
> Add hyper-transparent-dynamic

- README.md
> + hyper-white-theme

- README.md
> hyper-monochrome

- README.md
> Add hyper-seashells theme

- README.md
> hyper-clean theme

- README.md
> Add hyper-loved theme

- README.md
> Add hyper-firewatch theme

- README.md
- [ x ] **Title:** The title for the addition uses its npm title (`hyper-example`) or the resource's title.
- [ x ] **Link:** The link for the addition uses the npmjs.com link (`https://www.npmjs.com/package/hyper-example`) or the resource's full URI.
- [ x ] **Visual:** There is a visual representation of what the addition does in the addition's source repository.
- [ x ] **Location:** The awesome addition is at the **BOTTOM** of the correct category or sub-category.
- [ x ] **Description:** I've written a short (one sentence) description for the addition in the README.md.
- [ x ] **Downloads:** I've added a download stats …
> Add hyper-broadcast

- README.md
> Add hyper-hide-title plugin

- README.md
Since we always reply by telling them they should make a pull request, let's remove the part that says "Create an issue".
Even if they don't know how, it's a good opportunity to learn.
> Emphasize opening PRs for additions

- README.md
Adding a new theme to the list
The theme is based on the ayu light theme
> Add hyper-ayu-light theme

- README.md
Add the Ayu Mirage theme to the list
> Add Ayu Mirage theme

- README.md
> Added the `hyper-pokemon` theme

- README.md
> Add hyper-bloody theme

- README.md
> Add hyper-cat-cursor

- README.md
> Add hyper-search

- README.md
> Add hypergoogle

- README.md
> Add hyper-adventure-time

- README.md
> Add hyper-aurora

- README.md
This is a plugin that launches a rocket ship in your terminal when you commit code to Git.
- [x ] **Title:** The title for the addition uses its npm title (`hyper-example`) or the resource's title.
- [x ] **Link:** The link for the addition uses the npmjs.com link (`https://www.npmjs.com/package/hyper-example`) or the resource's full URI.
- [x ] **Repository:** The `package.json` file of the resource contains [repository information](https://docs.npmjs.com/files/package.json#repository).
- [x ] **Visual:** There is a visual representation of what the addition does in its source repository.
- [ x] **Location:** The awesome addition is in the correct category or sub-category.
- If it's a …
> Adds fun gitrocket plugin to README!

- README.md
> Added the `hyper-star-wars` theme

- README.md
> Add hyper-quit plugin

- README.md
> Add hyper-confirm plugin

- README.md
The plugin is really good, and slightly popular as well. It would be a great help for the plugin to make it to this list as well. It's a good alternative to transparency plugins and is useful for changing a terminal's background, a feature Hyper doesn't offer (yet). Similar terminals offer such features and I thought it would be great for Hyper to have such a feature. If this plugin makes it to this list, a lot more people will be aware about this plugin's features.
> Add hyper-background to the list.

- README.md
> Add hyper-vertical-tabs to Customization

- README.md
> Add link to themer under Customization package list.

- README.md
Hyper-match lets you bind triggers to patterns such as urls and emails.
> Add hyper-match to productivity

- README.md
I shipped my own Hyper theme a couple of days ago. Would be nice to have this one added to the list of Hyper themes 💯 
> Added "verminal" to list of Hyper themes.

- CONTRIBUTING.md
Fixess a link in CONTRIBUTING.md
> Fixed awesome-hyper link

- README.md
> Add new Ubuntu-style theme

- README.md
> Add plugin: hypergravity

- README.md
- Inspired by [gitrocket](https://www.npmjs.com/package/gitrocket)
- Runs landing rocket animation on successful 'git pull' command execution
> Add 'space-pull' plugin

- README.md
> Added hyper-bloodbath plugin to the Fun category

- README.md
> add hyper-systray ( Windows )

- README.md
> Add hyper-hide-scroll plugin to Customization category. 

- README.md
> Add hyper-visual

- README.md
> add hyper-window-size to Customization section

- README.md
Added the plugin `hyper-media-control` to the "Customization" section of the list.
> Added hyper-media-control to "Customization"

- README.md
> Add hyper-folder-icon in Customization section

- README.md
> added git-falcon9 plugin to readme

- README.md
[GitHub repo](https://github.com/slammayjammay/hyper-postprocessing)
This PR is a duplicate of #341, but I hard-reset to master and force pushed like an idiot so I'm creating a new one.
> Add hyper-postprocessing

- README.md
Added a reference to https://github.com/marcjoha/hyper-gcp-status-line which shows information about Google Cloud Platform resources.
> Added plugin hyper-gcp-status-line

- README.md
🙌 Thank you for making awesome-hyper. 
This PR adds Hyper's 🦄 [Shades of Purple theme](https://hyper.is/plugins/shades-of-purple-hyper) that I made. 
_P.S. [More SOP themes →](https://github.com/ahmadawais/shades-of-purple-vscode#put-shades-of-purple-in-other-places)_
> 📦 NEW: Shades of Purple theme

- README.md
> Add hyperinator

- README.md
https://www.npmjs.com/package/hyper-drop-file
add plugin hyper-drop-file which let user drop file path from file explorer into hyper terminal. 
> Add hyper-drop-file to plugins

- README.md
> Add hyper-dnd-tabs to productivity section

- README.md
> Add hyper-tabs-autohide plugin

- README.md
> Add hyper-manager plugin.
