bnb/awesome-hyper

README.md
This [package](https://www.npmjs.com/package/hyperterm-open-devtools) is used for toggle devtools for currently showing web page:
Use a configurable hotkey to open DevTools.
=> Add hyperterm-open-devtools

README.md
The `close-on-left` is a same feature in most of the macOS apps (Default terminal, iTerm2, Safari, Finder... etc).
=> Add hyperterm-close-on-left

README.md
=> Add hyperterm-hybrid theme

README.md
`hyperterm-title` set the title of your tabs to what your shell suggests. By default, hyperterm show on tabs the name of running process on macOS and "Shell" on Linux.
This plugin set the title of tabs in the same way that iTerm does.
=> Add hyperterm-title

README.md
=> Add hyperterm-mactabs plugin

README.md
=> Adds hyperterm-electron-highlighter

README.md
`hyperterm-final-say` let user's configuration overrides plugins'.
https://www.npmjs.com/package/hyperterm-final-say
=> Add `hyperterm-final-say` to packages.

README.md
Install DevTools extension via Chrome Web Store, it's based on [electron-devtools-installer](https://www.npmjs.com/package/electron-devtools-installer)
> Use [React Developer Tools](https://github.com/facebook/react-devtools) on web page (Open DevTools by [hyperterm-open-devtools](https://www.npmjs.com/package/hyperterm-open-devtools))
=> Add hyperterm-install-devtools

README.md
Keeping track of your current tab is not instantly visible in the native UI. `hyperterm-bold-tab` bold's the current tab's text so that you always know where you are!
Bolds the active tab to make keeping track of your current location simple.
=> Add hyperterm-bold-tab

README.md
Found a spelling error. Stuff is plural so there's no need to add an s.
=> Fix stuffs spelling error

README.md
`hyperterm-tab-icons` adds the awesome ability to show an icon based on the currently running process title!
=> Add `hyperterm-tab-icons` to Packages List

README.md
HyperTerm is more powerful than other terminals, so it's useful to be able to know if some Node.js code is running in HyperTerm to add extra functionality.
https://github.com/sindresorhus/is-hyperterm
=> Add `is-hyperterm` to Packages

README.md
https://github.com/philippbosch/hyperterm-dark-macos
=> Add hyperterm-dark-macos theme

README.md
Added the [materialshell](https://github.com/carloscuesta/materialshell) theme for HyperTerm.
=> Add hyperterm-materialshell

README.md
I wrote this little plugin to add focus gained & focus lost reporting when running terminal vim inside hyperterm.  This way when a terminal loses focus vim will receive the `focus lost` event & in my setup it autosaves all the buffers.  I don't think there's a really good way to show a visual representation of this, but I think I've hit every other item on the checklist!
=> Add hyperterm-focus-reporting

README.md
Add hyperfull plugin to plugin list. Hyperfull allows you to start Hyperterm in full screen size.
I've not added a visual representation of what my plugin or theme does because it's kind of self-explaining
=> Add hyperfull plugin

README.md
[The summary provided](https://github.com/bnb/awesome-hyper/blame/217e6c9bb9b36e448e70fb40bb77f023bc884826/README.md#L30) says:
> A plugin manager for HyperHyper
[The summary on npm](https://www.npmjs.com/package/hpm-cli) for hpm-cli says:
> A plugin manager for Hyper.app
Solves issue #120.
=> Fix typo in hpm-cli summary

README.md
=> added hyper-zigorat theme

README.md
This is the official [Material Theme](https://github.com/equinusocio/material-theme) porting for Hyper.
=> Add official material-theme for Hyper

README.md
Make the hyperterm close, minimize and maximize buttons look like a mac.
Link to repo: [hyper-mac-controls](https://github.com/krve/hyper-mac-controls)
=> Add new `hyper-mac-controls` to customization section

README.md
updated to accurate name from hyperterm-base16-ocean-saturated to hyper-oceans16 and more fitting description
=> change name hyperterm-base16-ocean-saturated

README.md
The link to hyperterm-tab-cwd was removed in https://github.com/bnb/awesome-hyper/pull/161 but later reintroduced in https://github.com/bnb/awesome-hyper/commit/2a518e84f9eac0ff2f442afa7534c929d2255c88. I didn't check if the latter introduced other regressions.
=> Remove (again) deprecated hyperterm-tab-cwd

README.md
This plugin is [deprecated](https://github.com/parro-it/hyperterm-title); its functionality is now baked in to Hyper by default.
=> Remove hyperterm-title

README.md
I am editing the name of an old repo I had for "HyperTerm" to "Hyper".
=> Editing my old repo name from hypertern-zenburn2 -> hyper-zenburn

README.md
Theme based on gruvbox with dark, light styles and contrast options.
https://www.npmjs.com/package/hyperterm-gruvbox
=> Add hyperterm-gruvbox theme

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, code-of-conduct.md
Updates to some basic contribution content in the repo, including adding a (missing) Contributor Code of Conduct, updating the CONTRIBUTING.md to be less of a direct copy and paste from `awesome`, and updating the PR template.
This was triggered by https://github.com/bnb/awesome-hyper/pull/175, which changed the way we needed to word some things in the guidelines and similar meta content.
@matheuss @iamstarkov @darahak Would be 💯 if you could review! 🙏
=> Update Contribution Guide

.github/PULL_REQUEST_TEMPLATE.md
It makes easier to find source code from npmjs
I'm using awesome-hyper to have a list of known plugins.
For a breaking change in `Hyper`, it permits to check all plugins repo and grep them to search impacted ones.
But for this, I need to retrieve source code. Without a repository entry in `package.json`, I can't use `npm view $plugin repository.url`.
I made PRs to correct these already listed plugins:
* hyperdocs
* hyperborder
* hyper-wal
* hyperpower
* hyper-white-theme
* hyper-zigorat
* hyperpanic
* hyperterm-cobalt2-theme
* hyperterm-colors
* hyperterm-electron-highlighter
* hyperterm-material-spacegray
* hyperterm-panda
=> Make repository in package.json mandatory

README.md
Native window decorations in HyperTerm.
Hyper uses it's own client-side decorations, and unless you're on a Mac, these decorations don't fit in well with the rest of the desktop environment. Using the platform's native window decorations is an easy way to make the terminal blend in.
=> Added 'hyper-native-window-decoration' to list of customization plugins

CONTRIBUTING.md
URL was no longer working since the file's repository name has changed.
=> Fix PR helper article url

README.md
1Password removed the functionality a while back.
=> hyperterm-1password no longer works

README.md
Added https://github.com/SwarShah/hyper-custom-touchbar which allows the user to add custom buttons in Macbook's Touch Bar.
=> Add hyper-custom-touchbar plugin

README.md
Add `hyper-save-windowstate` plugin to plugin list. `hyper-save-windowstate` saves and restores Hyper window position/size after restart.
I haven't added a visual representation of what my plugin does because its kind of self-explaining, so don't think it would be particularly helpful.
=> Add hyper-save-windowstate plugin

README.md
Added [hyperduck](https://github.com/benseven/hyperduck), which is a hypergoogle fork for DuckDuckGo.
=> Add hyperduck
